plugins:
  - tmuxp_plugin_loader.plugin.Loader
options:
  automatic-rename: on
synchronize-panes: on

windows:
  - window_name: editor
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
        - editor .

  - window_name: shell
    start_directory: .
    layout: even-horizontal
    panes:
      - pane

